steps:
  # Install node modules
  - name: 'node'
    entrypoint: 'npm'
    args: ['install']

  # Build the Next.js application
  - name: 'node'
    entrypoint: 'npm'
    args: ['run', 'build']

  # Install firebase-tools and deploy
  - name: 'node'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm install -g firebase-tools
        firebase deploy --project donodaoficina

# As the Service Account will have Firebase Admin permissions,
# we don't strictly need to pass credentials explicitly to the CLI here.
